platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
inputs:
  - name: repo-version
  - name: utils
outputs:
  - name: output
run:
  path: sh
  args:
  - -c
  - |
    VERSION=`cat repo-version/number`-SNAPSHOT && \
    utils/scripts/generate-download-artifact-xml.sh ${GROUP_ID} ${ARTIFACT_ID} ${VERSION} output && \
    mvn -f output/download-artifact.xml validate